name: Create Issue and PR

on:
  workflow_dispatch:

jobs:
  create-issue-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write        # needed for creating issues
      contents: write      # needed for pushing branch
      pull-requests: write # needed for creating PR
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Generate issue content
        run: echo "This is my test issue body" > issue.md

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Automated Test Issue"
          content-filepath: ./issue.md
          labels: |
            automated
            test

      - name: Clone source repo (example-content)
        run: |
          git clone https://github.com/peter-evans/create-issue-from-file.git source-repo
          cp -r source-repo/example-content ./example-content

      - name: Set branch name
        id: vars
        run: echo "branch=add-example-content-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Create new branch and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "${{ steps.vars.outputs.branch }}"
          git add example-content
          git commit -m "Add example-content from peter-evans/create-issue-from-file"
          git push origin "${{ steps.vars.outputs.branch }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.vars.outputs.branch }}
          base: main
          title: "Add example-content directory"
          body: "This PR adds the example-content directory copied from peter-evans/create-issue-from-file."
