name: Create Issue and Copy Next.js Docs

on:
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docs from Next.js
        run: |
          git clone --depth 1 https://github.com/vercel/next.js.git nextjs
          rm -rf ./docs                   # remove old docs in your repo
          cp -r nextjs/docs ./docs        # copy fresh docs
          rm -rf nextjs                   # clean up

      - name: Generate issue file
        run: echo "Docs sync triggered" > output.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          branch: sync-nextjs-docs
          base: main
          title: "Sync Next.js Docs"
          body: |
            This PR syncs the **docs** directory from vercel/next.js.

            It also includes an auto-generated issue file for tracking.
          add-paths: |
            docs/**
            output.md
