name: Create Issue

on:
  workflow_dispatch:  # allows you to trigger manually from the Actions tab

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Issue"
          body: |
            This issue was automatically created by a GitHub Action.
