name: Create Issue

on:
  workflow_dispatch:  # allows you to trigger manually from the Actions tab

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: An example issue
          content-filepath: /output.md
          labels: |
            report
            automated issue
