name: Create Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: An example issue
          content-filepath: ./output.md   # relative to repo root
          labels: |
            report
            automated issue
